name: Kong E2E Tests

on:
  push:
    branches: [main]
  workflow_dispatch:
      
jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Merge mochawesome JSON files
        run: |
          npx mochawesome-merge cypress/reports/mocha*.json > cypress/reports/output.json
          npx marge cypress/reports/output.json -f report -o cypress/reports/mochawesome-report

      - name: Read report HTML into email body
        id: read_report
        shell: bash
        run: |
          echo "body<<EOF" >> $GITHUB_OUTPUT
          cat cypress/reports/mochawesome-report/report.html >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send email with report
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.qq.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚀 Kong Gateway E2E Tests Report - ${{ github.repository }}"
          from: "Kong CI Bot <${{ secrets.EMAIL_USERNAME }}>"
          to: xuerenbo@qq.com
          html_body: true
          body: ${{ steps.read_report.outputs.body }}
          attachments: cypress/reports/mochawesome-report/report.html