name: Kong E2E Tests

on:
  push:
    branches: [main]
  workflow_dispatch:
      
jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Merge mochawesome JSON files
        run: |
          npx mochawesome-merge cypress/reports/mocha*.json > cypress/reports/output.json
          npx marge cypress/reports/output.json -f report -o cypress/reports/mochawesome-report

      - name: Read report HTML into email body
        id: read_report
        run: |
          CONTENT=$(base64 -w 0 cypress/reports/mochawesome-report/report.html)
          echo "content=$CONTENT" >> $GITHUB_OUTPUT

      - name: Upload HTML report artifact
        uses: actions/upload-artifact@v3
        with:
          name: mochawesome-report
          path: cypress/reports/mochawesome-report/report.html

      - name: Send email with report
        uses: mattdavis0351/actions-send-email@v1
        with:
          server_address: smtp.qq.com
          server_port: 587
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚀 Kong Gateway E2E Tests Report - ${{ github.repository }}"
          from: "Kong CI Bot <${{ secrets.EMAIL_USERNAME }}}>"
          to: xuerenbo@qq.com
          html_body: true
          body: ${{ steps.read_report.outputs.content }}
          attachments: cypress/reports/mochawesome-report/report.html