name: Kong E2E Tests

on:
  push:
    branches: [main]
  workflow_dispatch:
      
jobs:
  cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install Dependencies
        run: npm install

      - name: Run Cypress Tests
        run: npx cypress run

      - name: Merge mochawesome JSON files
        run: |
          npx mochawesome-merge cypress/reports/mocha*.json > cypress/reports/output.json
          npx marge cypress/reports/output.json -f report -o cypress/reports/mochawesome-report

      - name: Parse test summary and set as email body
        id: summary
        shell: bash
        run: |
          STATS=$(jq '.stats' cypress/reports/output.json)
          TESTS=$(echo "$STATS" | jq '.tests')
          PASSES=$(echo "$STATS" | jq '.passes')
          FAILURES=$(echo "$STATS" | jq '.failures')
          DURATION_MS=$(echo "$STATS" | jq '.duration')
          DURATION_MIN=$(awk "BEGIN {print int($DURATION_MS / 60000)}")
          DURATION_SEC=$(awk "BEGIN {print int(($DURATION_MS % 60000) / 1000)}")
          
          {
            echo "body<<EOM"
            echo "<p>Kong Gateway E2E tests completed</p>"
            echo "<ul>"
            echo "<li>Total tests: $TESTS</li>"
            echo "<li>Passed: $PASSES</li>"
            echo "<li>Failed: $FAILURES</li>"
            echo "<li>Duration: $DURATION_MIN min $DURATION_SEC sec</li>"
            echo "</ul>"
            echo "<p>See attached HTML report for full details.</p>"
            echo "EOM"
          } >> $GITHUB_OUTPUT

      - name: Debug email body
        run: echo "${{ steps.summary.outputs.body }}"

      - name: Send email with report
        uses: dawidd6/action-send-mail@v5
        with:
          server_address: smtp.qq.com
          server_port: 465
          secure: true
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "🚀 Kong Gateway E2E Tests Report - ${{ github.repository }}"
          from: "Kong CI Bot <${{ secrets.EMAIL_USERNAME }}>"
          to: xuerenbo@qq.com
          html_body: "true"
          body: "${{ steps.summary.outputs.body }}"
          attachments: cypress/reports/mochawesome-report/report.html